### ISSUE TITLE
Automatically reference the assets on the log forms

### ISSUE THREAD

**Issue by pcambra** [mstenta/farm_nfa#132]
Reference all the assets from all the compartments selected on the location field to the log created/edited.

**Comment by pcambra** [comment]
I've changed this but not sure how to verify, @mstenta

**Comment by mstenta** [comment]
I think we only want to reference `forest` assets in the `asset` field of logs, and `compartment` assets in the `location` field.

> - When a log uses the Asset field, it means "this happened TO this asset".
> - When a log uses the Location field, it means "this happened IN this asset".

This way, we will be able to track what happened to the Forest assets, which are the primary assets that will be managed for harvests, plantings, etc, but we will also be able to see *where* this activities occurred, in order to build a longer-term history of each compartment (which will span longer than the Forest assets, in theory).

So, the thought was: when a user fills out one of the forms for creating a log (via the Management, Inventory, or Harvest tabs), they would select the Compartment as a first step (to narrow down *where* the action took place). Then, when the log is saved, it would a) reference the selected Compartment asset(s) in the Location field on the log, and it would perform a look-up to find all the Forest assets currently "located within" those Compartments, and reference them in the Asset field of the Log.

The Asset Location service can be used to find all assets in a given location. For example:

```
$assets = \Drupal::service('asset.location')->getAssetsByLocation($locations);
```

https://docs.farmos.org/development/module/services/#asset-location-service

In the above example, `$locations` would be an array of `compartment` assets, and `$assets` would be *all* assets currently located in those Compartments. We need to also filter out assets that are not type `forest` after that (just in case).

**Comment by pcambra** [comment]
closing this in favor of #92
