### ISSUE TITLE
Adapt the migrations to the new asset type structure

### ISSUE THREAD

**Issue by pcambra** [mstenta/farm_nfa#66]
I need @mstenta support with this

**Comment by pcambra** [comment]
Forest migrations need to default as natural stands

**Comment by mstenta** [comment]
@pcambra I pushed a `2.x-migration-updates` branch that makes the necessary changes: https://github.com/mstenta/farm_nfa/compare/2.x...2.x-migration-updates

This is ready to be re-run, but there are a few things to note (waiting for feedback from @LeScruf in email thread subject "Migration questions":

- Areas of type `nursery` in the old database are migrated to Forest assets of type `plantation` in the new database. I'm not sure if this is desirable, or if something special will be needed for Nurseries. Worth noting that Nurseries are the ONLY migrated Forest assets now. Previously Compartments also migrated to Forest assets, but now there is a dedicated Compartment asset.
- Areas of type `cfr_plantation`, `cfr_natural`, and `cfr_urban` are all migrated to CFR assets now, although this distinction between "plantation", "natural", and "urban" is not maintained in the new database. I don't think we have a field on the CFR assets for this, and it may point to the fact that the old database's representation is fuzzy/unclear (should they actually be Forest assets, perhaps?)

So, we may need to change a few other things once after discussing these things with @LeScruf. But I think you can re-run this migration in the meantime anyways, if it's easy.

One additional change included in this branch is the removal of the "Zone" land type - because Zones are their own asset type now.

**Comment by mstenta** [comment]
Assigning to you @pcambra - feel free to merge `2.x-migration-updates` into `2.x` if everything works!

**Comment by pcambra** [comment]
Re-migration instructions:

- Rollback current migrations
- Update the code and make sure this is included https://github.com/farmOS/farm_forest/commit/fc1876e6a49ebcd746b737273c7ef12fbc220c48#diff-09c95abe06dafd7db62b6edd721c647913348ea3502f8071424fa7d060ba78fd
- Import migration configs:
```
    farm_migrate_area_nfa_cfr
    farm_migrate_area_nfa_compartment
    farm_migrate_area_nfa_zone
```

- Revert land and forest migrations
- Delete farm_land.land_type.zone config
- Run the migrations again

**Comment by pcambra** [comment]
@LeScruf the migration has been adapted to the new asset types and the data updated on the live environment.
