### ISSUE TITLE
Expose file upload field for KML uploads

### ISSUE THREAD

**Issue by pcambra** [mstenta/farm_nfa#93]

**Comment by mstenta** [comment]
Depends on #94

**Comment by mstenta** [comment]
Actually @pcambra in theory this only requires adding the `file` field alongside the `geometry` field in the form view mode(s). And then once #94 happens (farmOS 2.0.0-alpha3) then the "Import Geometry from uploaded files" button *should* automatically appear below the `geometry` map, and it will "just work"!

So maybe a first step is to simply add the `file` field to the view mode? I will assign to you since you have a better understanding of that side of things.

Then maybe we can leave this open until #94 happens, and test to make sure it works as expected before closing this.

**Comment by pcambra** [comment]
This is now ready to evaluate

**Comment by LeScruf** [comment]
It's not immediately obvious in the workflow how one uploads the kml once it has been selected from a local source using the browse button?

**Comment by pcambra** [comment]
@LeScruf could you send me a example KML to test this?

**Comment by pcambra** [comment]
Error on upload regarding serialization:

The website encountered an unexpected error. Please try again later.Exception: Serialization of &#039;Symfony\\Component\\HttpFoundation\\File\\UploadedFile&#039; is not allowed in serialize()
